### ISSUE TITLE
How to check if function is called via Function Wizard

### ISSUE THREAD

**Issue by lewismj** [xlw/xlw-Examples#1]
Hi,
I'm sure I've missed something, but could you help - is there an example where you check if a function is being called from within the Excel Wizard ? i.e. I'd like to be able to trap the cases where function is called from Wizard and not execute (but show help etc...)
Thanks,
Mike

**Comment by JohnAdders** [comment]
See https://github.com/xlw/xlw-Examples/blob/master/Handwritten/HandWritten/xlwExample.cpp and the xlIsInWiz function.
The function XlfExcel::Instance().IsCalledByFuncWiz() return true if called from the wizard

**Comment by MarcoPolo314** [comment]
What's wrong with a function being called from the Wizard?

**Comment by MarcoPolo314** [comment]
What's wrong with a function being called from the Wizard? @lewismj @JohnAdders

**Comment by lewismj** [comment]
@MarcoPolo314 - some times you have long running function, and you will want to suppress the call if someone is just examining the inputs in Excel..
